language: node_js
node_js:
- '5'
before_deploy:
- npm run build
addons:
  code_climate:
    repo_token: 44eee1f4893752df2d19d19818f3b94ae3d4daff51d2f866c70f0deab98d8db6
before_script:
- npm install -g codeclimate-test-reporter
after_script:
- npm run coverage
- codeclimate-test-reporter < coverage/lcov.info
deploy:
  provider: npm
  email: serveradmin@octoblu.com
  skip_cleanup: true
  on:
    tags: true
  api_key:
    secure: 4o3FiUhuYMOo4ks1+pEygUrqlS1GrVPpiNrc8NyqLAs91dj2H1bN/Sor9tsGrZwSTqQNNPST1b6QZhTsyrI5WUoGx9Nn5+/ZQNa5ydiAekcUAFNkj4yttICEANG3W2/08lVv4eE8rnP7HsGT75KHHjIVbvcL93BqAXCHA6FY1auNdPGMeYXmIqVHZ//rq9driKRpN6xcn3m4JyJHX3d9w6PSY5JFOJ/QYRvnZSQykC7RJQQGnCgG31mrIGlqVKOgs6ni6MTKJ5TluJ08WwbeLWcJ0ampO3srgr9duzz96vkfdpJYwbMVXyMYSz3JJtiiRwoDFj6UgLM77uDB6v1tp8VGFglmQxUg78rF9rBauy1HS8sd1a7qPizc2yJRCWuzy7wbl4RviqLoL+qT+1+soRjQo5nuu9n/d8e0A3mYN9Si2rcKEuLSjWOXmSWqXHmhFpU0RZi3SOri/HCpq8+0ZnjC/+fRQm4cDhaYyX+XpIcDM97pLKD6DA5NRYPHsOdLOr64vdSoeLcXHVth+XDAPcONiuAtF5VfxmPAQB2eCSPs58mOwaDZ6bb6T7XHzCOV7DJ/UeKiFKVdjRlRbm2awe+2JyhSwsMpZGUH7BA1Sfwk8MI0Sbs18+QtHI9G3Q3oUUpw57VNRdM6yTY37rjxIugenKQ+kHkbrAm6L4gkMeg=
after_success:
- bash <(curl -s https://codecov.io/bash)
branches:
  only:
  - "/^v[0-9]/"
